### Open test endpoint
GET {{ apigw_url}}/echo

### Obtain token before authenticated operations
GET {{ apigw_url}}/token
Authorization: Basic {{basicAuth_user}} {{basicAuth_pass}}

### Protected test endpoint
# Set the IdToken to the env file after obtaining the result
GET {{ apigw_url}}/echo-auth
Authorization: Bearer {{idToken}}

### Example of real app endpoint
GET {{ apigw_url}}/jobs
Authorization: Bearer {{idToken}}

